language: python
sudo: required
virtualenv: 
  system_site_packages: true
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # PyPy versions
  #- "pypy"  # PyPy2 2.5.0
  #- "pypy3" # Pypy3 2.4.0
  #- "pypy-5.3.1"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-dbus python3-dbus
install:
  - pip install .
#  - pip install -r requirements.txt
# command to run tests
script: py.test
